Se crea filtro para ItemsTable
Franco-Borghi/henry-pf-front pull request #116
Opened 2023-06-07 21:50 UTC by jopez1

2023-06-08 01:08 UTC, RamiroRob commented on src/components/AdminDashboard/ItemsTable/ItemsTable.jsx
>          console.log(response.data);
Ya tenemos motorcycles en el reducer, no hace falta hacer la request a la API

2023-06-08 01:08 UTC, RamiroRob commented on src/components/AdminDashboard/ItemsTable/ItemsTable.jsx
>      setEditData((prevEditData) => ({
No vamos a dejar editar el chassisId al final

2023-06-08 01:10 UTC, RamiroRob commented on src/components/AdminDashboard/ItemsTable/ItemsTable.jsx
> +          moto.model.toLowerCase().includes(searchQuery.toLowerCase())
Fijate como refactorizamos el codigo en users y motorcycleTable. Manejamos los filtros con useEffect.

Pero ademas, vos no tenes un valor "active" en una columna. esto deberia romper el codigo, no?

2023-06-08 01:11 UTC, RamiroRob requested changes
Hola Antonio, ahi te deje varios comentarios. 

Igual, me parece que lo mas facil seria copiar la tabla de franco (users) o la mia (motorcyclesTable) y empezar desde ahi. Tenemos varios cambios con estilos y tmb con la logica, paginado y search bar. 

Ademas te puse varias observaciones de cosas que creo que hay que cambiar.

2023-06-08 15:34 UTC, jopez1 commented on src/components/AdminDashboard/ItemsTable/ItemsTable.jsx
>      setEditData((prevEditData) => ({
Entonces quito el boton de "Edit" y "Delete" ya que al final no se van a utilizar?

2023-06-09 01:05 UTC, ivand2004 approved these changes

2023-06-09 15:06 UTC, closed without merging